// 다국어 지원 텍스트
export const translations = {
    ko: {
        appName: '🌱 루틴 체인',
        appSubtitle: '작은 습관이 모여 위대한 변화를 만듭니다.',
        navToday: '오늘의 할 일',
        navHabits: '습관 관리',
        navRoutines: '루틴 만들기',
        navStats: '통계',
        todayTitle: '오늘의 할 일',
        habitsTitle: '습관 씨앗들',
        routinesTitle: '루틴 관리',
        statsTitle: '통계',
        completed: '완료',
        routinesSection: '루틴',
        habitsSection: '개별 습관',
        addHabitPlaceholder: '새로운 습관 씨앗 심기',
        add: '추가',
        newRoutine: '+ 새로운 루틴 만들기',
        modalNewRoutineTitle: '새로운 루틴 만들기',
        modalEditRoutineTitle: '루틴 수정',
        routineNamePlaceholder: '루틴 이름',
        selectHabitsPrompt: '포함할 습관들을 선택해주세요.',
        save: '저장',
        delete: '삭제',
        deleteHabitConfirm: '이 습관을 삭제하면 모든 루틴에서도 제거됩니다. 정말 삭제하시겠습니까?',
        deleteRoutineConfirm: '이 루틴을 정말 삭제하시겠습니까?',
        deleteGroupConfirm: '이 그룹을 삭제하시겠습니까? 그룹에 속한 루틴들은 그룹 없음 상태가 됩니다.',
        habitDeleted: '습관이 삭제되었습니다.',
        habitDeleteError: '오류가 발생하여 습관을 삭제하지 못했습니다.',
        routineDeleted: '루틴이 삭제되었습니다.',
        routineDeleteError: '오류가 발생하여 루틴을 삭제하지 못했습니다.',
        groupDeleted: '그룹이 삭제되었습니다.',
        groupDeleteError: '오류가 발생하여 그룹을 삭제하지 못했습니다.',
        duplicateHabitError: '이미 동일한 이름의 습관이 존재합니다.',
        addHabitError: '오류가 발생하여 습관을 추가하지 못했습니다.',
        saveRoutineError: '오류가 발생하여 루틴을 저장하지 못했습니다.',
        saveRoutineSuccess: '루틴이 저장되었습니다.',
        saveGroupSuccess: '그룹이 저장되었습니다.',
        updateRoutineSuccess: '루틴이 수정되었습니다.',
        updateGroupSuccess: '그룹이 수정되었습니다.',
        routineValidationError: '루틴 이름과 하나 이상의 습관을 선택해주세요.',
        groupValidationError: '그룹 이름을 입력해주세요.',
        calendarMonthTitle: (year: number, month: number) => `${year}년 ${month}월`,
        calendarDays: ['일', '월', '화', '수', '목', '금', '토'],
        dailyRecordTitle: (date: string) => `${date} 기록`,
        noCompletedHabits: '이 날은 완료된 습관이 없습니다.',
        cancel: '취소',
        confirm: '확인',
        googleLogin: 'Google 계정으로 로그인',
        logout: '로그아웃',
    },
    en: {
        appName: '🌱 Routine Chain',
        appSubtitle: 'Small habits create great change.',
        navToday: "Today's Tasks",
        navHabits: 'Manage Habits',
        navRoutines: 'Manage Routines',
        navStats: 'Statistics',
        todayTitle: "Today's Tasks",
        habitsTitle: 'My Habit Seeds',
        routinesTitle: 'Manage My Routines',
        statsTitle: 'Statistics',
        completed: 'Completed',
        routinesSection: 'Routines',
        habitsSection: 'Individual Habits',
        addHabitPlaceholder: 'Plant a new habit seed',
        add: 'Add',
        newRoutine: '+ Create New Routine',
        modalNewRoutineTitle: 'Create New Routine',
        modalEditRoutineTitle: 'Edit Routine',
        routineNamePlaceholder: 'Routine Name',
        selectHabitsPrompt: 'Please select habits to include.',
        save: 'Save',
        delete: 'Delete',
        deleteHabitConfirm: 'Deleting this habit will also remove it from all routines. Are you sure?',
        deleteRoutineConfirm: 'Are you sure you want to delete this routine?',
        deleteGroupConfirm: 'Are you sure you want to delete this group? Routines in this group will become ungrouped.',
        habitDeleted: 'Habit deleted.',
        habitDeleteError: 'Error: Could not delete habit.',
        routineDeleted: 'Routine deleted.',
        routineDeleteError: 'Error: Could not delete routine.',
        groupDeleted: 'Group deleted.',
        groupDeleteError: 'Error: Could not delete group.',
        duplicateHabitError: 'A habit with the same name already exists.',
        addHabitError: 'Error: Could not add habit.',
        saveRoutineError: 'Error: Could not save routine.',
        saveRoutineSuccess: 'Routine saved.',
        saveGroupSuccess: 'Group saved.',
        updateRoutineSuccess: 'Routine updated.',
        updateGroupSuccess: 'Group updated.',
        routineValidationError: 'Please enter a routine name and select at least one habit.',
        groupValidationError: 'Please enter a group name.',
        calendarMonthTitle: (year: number, month: number) => `${new Date(year, month - 1).toLocaleString('en-US', { month: 'long' })} ${year}`,
        calendarDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        dailyRecordTitle: (date: string) => `Records for ${date}`,
        noCompletedHabits: 'No habits were completed on this day.',
        cancel: 'Cancel',
        confirm: 'Confirm',
        googleLogin: 'Sign in with Google',
        logout: 'Logout',
    }
};
