import React from 'react';

const lightTheme = {
    background: '#F3F4F6',
    content: '#FFFFFF',
    card: '#FFFFFF',
    text: '#1F2937',
    subtext: '#6B7280',
    primary: '#3B82F6',
    primaryActive: '#3B82F6',
    primaryText: '#FFFFFF',
    secondaryText: '#4B5563',
    secondaryTextActive: '#3B82F6',
    border: '#E5E7EB',
    inputBackground: '#FFFFFF',
    inputText: '#1F2937',
    inputBorder: '#D1D5DB',
    disabled: '#D1D5DB',
    groupColor: '#6D28D9',
    groupBorder: '#8B5CF6',
};

const darkTheme = {
    background: '#111827',
    content: '#1F2937',
    card: '#1F2937',
    text: '#F9FAFB',
    subtext: '#9CA3AF',
    primary: '#60A5FA',
    primaryActive: '#60A5FA',
    primaryText: '#111827',
    secondaryText: '#9CA3AF',
    secondaryTextActive: '#60A5FA',
    border: '#374151',
    inputBackground: '#374151',
    inputText: '#F9FAFB',
    inputBorder: '#4B5563',
    disabled: '#4B5563',
    groupColor: '#A78BFA',
    groupBorder: '#A78BFA',
};

export const getStyles = (isDarkMode: boolean): any => {
    const theme = isDarkMode ? darkTheme : lightTheme;

    const baseStyles = {
        theme,
        container: { display: 'flex', flexDirection: 'column', height: '100vh', backgroundColor: theme.background, fontFamily: 'sans-serif', color: theme.text },
        centerContainer: { display: 'flex', flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: theme.background },
        loadingText: { fontSize: 18, color: theme.subtext },
        appHeader: { backgroundColor: theme.content, padding: '20px', borderBottom: `1px solid ${theme.border}` },
        appHeaderTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
        appHeaderTitle: { fontSize: 24, fontWeight: 'bold', color: theme.text, margin: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
        appHeaderSubtitle: { fontSize: 14, color: theme.subtext, marginTop: 4, margin: 0, textAlign: 'center' },
        headerActions: { display: 'flex', alignItems: 'center' },
        langSwitcher: { display: 'flex', border: `1px solid ${theme.inputBorder}`, borderRadius: '8px', marginRight: '12px' },
        langButton: { background: 'none', border: 'none', padding: '4px 8px', cursor: 'pointer', color: theme.secondaryText },
        langButtonActive: { background: theme.primary, border: 'none', padding: '4px 8px', cursor: 'pointer', color: theme.primaryText, borderRadius: '7px' },
        logoutButton: { background: '#EF4444', color: 'white', border: 'none', padding: '4px 12px', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold' },
        content: { flex: 1, overflowY: 'auto', backgroundColor: theme.background },
        navigation: { display: 'flex', flexDirection: 'row', backgroundColor: theme.content, borderTop: `1px solid ${theme.border}`, width: '100%' },
        navButtonText: { fontSize: 12, color: 'inherit', marginTop: 4, margin: 0 },
        navButtonTextActive: { color: theme.secondaryTextActive, fontWeight: 'bold' },
        viewContainer: { padding: 20 },
        viewTitle: { fontSize: 22, fontWeight: 'bold', color: theme.text, marginBottom: 20, margin: 0 },
        card: { backgroundColor: theme.card, borderRadius: 12, padding: 20, marginBottom: 16, boxShadow: isDarkMode ? "0 2px 4px rgba(0,0,0,0.3)" : "0 2px 4px rgba(0,0,0,0.1)" },
        cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
        cardTitle: { fontSize: 18, fontWeight: 'bold', color: theme.text, margin: 0 },
        habitItem: { display: 'flex', flex: 1, flexDirection: 'row', alignItems: 'center', padding: '12px 0', borderBottom: `1px solid ${theme.border}` },
        habitText: { marginLeft: 12, fontSize: 16, color: theme.text, margin: 0 },
        habitTextCompleted: { textDecoration: 'line-through', color: theme.subtext },
        emptyStateSubText: { fontSize: 14, color: theme.subtext, marginTop: 8, textAlign: 'center', margin: 0 },
        inputContainer: { display: 'flex', flexDirection: 'row', marginBottom: 20 },
        input: { flex: 1, backgroundColor: theme.inputBackground, color: theme.inputText, padding: '12px 16px', borderRadius: 8, fontSize: 16, marginRight: 8, border: `1px solid ${theme.inputBorder}` },
        addButton: { backgroundColor: theme.primary, padding: '0 20px', borderRadius: 8, display: 'flex', justifyContent: 'center', alignItems: 'center', border: 'none', cursor: 'pointer' },
        addButtonText: { color: theme.primaryText, fontWeight: 'bold', fontSize: 16, margin: 0 },
        listItem: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: theme.card, padding: '0 16px', borderRadius: 8, marginBottom: 8, borderBottom: `1px solid ${theme.border}` },
        transparentButton: { background: 'none', border: 'none', cursor: 'pointer', padding: '8px' },
        bigAddButton: { backgroundColor: theme.primary, borderRadius: 8, padding: 16, alignItems: 'center', marginBottom: 20, border: 'none', width: '100%', cursor: 'pointer' },
        bigAddButtonText: { color: theme.primaryText, fontSize: 16, fontWeight: 'bold', margin: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' },
        modalContainer: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, display: 'flex', justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)', zIndex: 1000 },
        modalContent: { backgroundColor: theme.card, color: theme.text, borderRadius: 20, padding: 20, width: '90%', maxWidth: 500, maxHeight: '80vh', display: 'flex', flexDirection: 'column' },
        closeButton: { alignSelf: 'flex-end', background: 'none', border: 'none', cursor: 'pointer' },
        modalTitle: { fontSize: 22, fontWeight: 'bold', marginBottom: 20, textAlign: 'center', margin: 0, color: theme.text },
        modalSubtitle: { fontSize: 16, color: theme.subtext, marginBottom: 12, marginTop: 12, margin: 0 },
        habitSelectionContainer: { flex: 1, overflowY: 'auto', border: `1px solid ${theme.border}`, borderRadius: 8, padding: '0 10px' },
        habitSelectItem: { display: 'flex', flexDirection: 'row', alignItems: 'center', padding: '12px 0', borderBottom: `1px solid ${theme.border}`, cursor: 'pointer' },
        habitSelectText: { marginLeft: 12, fontSize: 16, margin: 0, color: theme.text },
        saveButton: { backgroundColor: '#10B981', borderRadius: 8, padding: 16, alignItems: 'center', marginTop: 20, border: 'none', width: '100%', cursor: 'pointer' },
        saveButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold', margin: 0 },
        routineHabitItem: { display: 'flex', flexDirection: 'row', alignItems: 'center', padding: '8px 0' },
        routineHabitText: { fontSize: 16, color: theme.text, margin: 0 },
        progressBarContainer: { height: 8, backgroundColor: isDarkMode ? '#4B5563' : '#E5E7EB', borderRadius: 4, marginBottom: 8, overflow: 'hidden' },
        progressBar: { height: '100%', backgroundColor: theme.primary, borderRadius: 4, transition: 'width 0.3s ease' },
        progressText: { fontSize: 12, color: theme.subtext, textAlign: 'right', marginBottom: 10, margin: 0 },
        statsHighlight: { fontSize: 18, fontWeight: 'bold', color: theme.primary, margin: '4px 0 16px' },
        statsSubtitle: { fontSize: 16, fontWeight: '500', color: theme.text, marginBottom: 8 },
        statsListItem: { display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: `1px solid ${theme.border}` },
        calendarNav: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' },
        calendarGrid: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '1vw', textAlign: 'center', padding: '1vw' },
        calendarHeader: { fontWeight: 'bold', fontSize: '3vw', color: theme.subtext, marginBottom: '1vw' },
        calendarDay: { 
            aspectRatio: '1 / 1', 
            display: 'flex', 
            flexDirection: 'column',
            justifyContent: 'center', 
            alignItems: 'center', 
            borderRadius: '8px', 
            cursor: 'pointer', 
            borderWidth: '2px',
            borderStyle: 'solid',
            borderColor: 'transparent',
            position: 'relative',
            padding: '0.5vw',
            transition: 'all 0.2s ease-in-out',
        },
        calendarDaySelected: { borderColor: theme.primary, transform: 'scale(1.05)' },
        calendarDayNumber: { fontSize: '2.5vw', color: theme.text, fontWeight: '500' },
        calendarDayFraction: { fontSize: '2.2vw', fontWeight: 'bold', color: theme.text },
        calendarTodayMarker: { position: 'absolute', top: '4px', right: '4px', width: '6px', height: '6px', backgroundColor: '#EF4444', borderRadius: '50%' },
        notificationContainer: { position: 'fixed', top: '20px', left: '50%', transform: 'translateX(-50%)', backgroundColor: '#333', color: 'white', padding: '12px 24px', borderRadius: '8px', zIndex: 2000, boxShadow: '0 4px 6px rgba(0,0,0,0.1)', transition: 'opacity 0.5s ease' },
        notificationText: { margin: 0, fontWeight: '500' },
        confirmModalContent: { backgroundColor: theme.card, borderRadius: 20, padding: 30, width: '90%', maxWidth: 400, textAlign: 'center', boxShadow: "0 4px 12px rgba(0,0,0,0.15)" },
        confirmButtonContainer: { display: 'flex', justifyContent: 'center', gap: '12px', marginTop: '20px' },
        confirmButton: { padding: '10px 20px', borderRadius: 8, border: 'none', cursor: 'pointer', fontWeight: 'bold', fontSize: 16 },
        cancelButton: { backgroundColor: isDarkMode ? '#4B5563' : '#E5E7EB', color: theme.text },
        okButton: { backgroundColor: theme.primary, color: 'white' },
        groupColor: { color: theme.groupColor },
    };

    return {
        ...baseStyles,
        navButton: {
            flex: 1,
            padding: 12,
            alignItems: 'center',
            justifyContent: 'center',
            background: 'none',
            borderWidth: 0,
            cursor: 'pointer',
            borderTopWidth: '2px',
            borderTopStyle: 'solid',
            borderTopColor: 'transparent',
            color: theme.secondaryText
        },
        navButtonActive: {
            borderTopColor: theme.primaryActive,
            color: theme.secondaryTextActive,
            fontWeight: 'bold',
        },
        tabContainer: {
            display: 'flex',
            overflowX: 'auto',
            marginBottom: '16px',
            paddingBottom: '10px',
            borderBottom: `1px solid ${theme.border}`
        },
        tabButton: {
            padding: '8px 16px',
            whiteSpace: 'nowrap',
            border: 'none',
            borderBottom: '2px solid transparent',
            color: theme.subtext,
            background: 'none',
            cursor: 'pointer',
            fontSize: '14px',
        },
        tabButtonActive: {
            padding: '8px 16px',
            whiteSpace: 'nowrap',
            border: 'none',
            borderBottom: `2px solid ${theme.primary}`,
            color: theme.primary,
            fontWeight: 'bold',
            background: 'none',
            cursor: 'pointer',
            fontSize: '14px',
        },
    };
};