import React from 'react';

// 스타일 객체
export const styles: { [key: string]: React.CSSProperties } = {
    container: { display: 'flex', flexDirection: 'column', height: '100vh', backgroundColor: '#F3F4F6', fontFamily: 'sans-serif' },
    centerContainer: { display: 'flex', flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F3F4F6' },
    loadingText: { fontSize: 18, color: '#4B5563' },
    appHeader: { backgroundColor: '#FFFFFF', padding: '20px', borderBottom: '1px solid #E5E7EB' },
    appHeaderTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    appHeaderTitle: { fontSize: 24, fontWeight: 'bold', color: '#1F2937', margin: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
    appHeaderSubtitle: { fontSize: 14, color: '#6B7280', marginTop: 4, margin: 0, textAlign: 'center' },
    headerActions: { display: 'flex', alignItems: 'center' },
    langSwitcher: { display: 'flex', border: '1px solid #D1D5DB', borderRadius: '8px', marginRight: '12px' },
    langButton: { background: 'none', border: 'none', padding: '4px 8px', cursor: 'pointer', color: '#4B5563' },
    langButtonActive: { background: '#3B82F6', border: 'none', padding: '4px 8px', cursor: 'pointer', color: 'white', borderRadius: '7px' },
    logoutButton: { background: '#EF4444', color: 'white', border: 'none', padding: '4px 12px', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold' },
    content: { flex: 1, overflowY: 'auto' },
    navigation: { display: 'flex', flexDirection: 'row', backgroundColor: '#FFFFFF', borderTop: '1px solid #E5E7EB' },
    navButton: {
        flex: 1,
        padding: 12,
        alignItems: 'center',
        justifyContent: 'center',
        background: 'none',
        borderWidth: 0,
        cursor: 'pointer',
        borderTopWidth: '2px',
        borderTopStyle: 'solid',
        borderTopColor: 'transparent'
    },
    navButtonActive: {
        borderTopColor: '#3B82F6'
    },
    navButtonText: { fontSize: 12, color: '#4B5563', marginTop: 4, margin: 0 },
    navButtonTextActive: { color: '#3B82F6', fontWeight: 'bold' },
    viewContainer: { padding: 20 },
    viewTitle: { fontSize: 22, fontWeight: 'bold', color: '#11182C', marginBottom: 20, margin: 0 },
    card: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 20, marginBottom: 16, boxShadow: "0 2px 4px rgba(0,0,0,0.1)" },
    cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    cardTitle: { fontSize: 18, fontWeight: 'bold', color: '#1F2937', margin: 0 },
    habitItem: { display: 'flex', flex: 1, flexDirection: 'row', alignItems: 'center', padding: '12px 0', borderBottom: '1px solid #F3F4F6' },
    habitText: { marginLeft: 12, fontSize: 16, color: '#374151', margin: 0 },
    habitTextCompleted: { textDecoration: 'line-through', color: '#9CA3AF' },
    emptyStateSubText: { fontSize: 14, color: '#9CA3AF', marginTop: 8, textAlign: 'center', margin: 0 },
    inputContainer: { display: 'flex', flexDirection: 'row', marginBottom: 20 },
    input: { flex: 1, backgroundColor: '#FFFFFF', padding: '12px 16px', borderRadius: 8, fontSize: 16, marginRight: 8, border: '1px solid #D1D5DB' },
    addButton: { backgroundColor: '#3B82F6', padding: '0 20px', borderRadius: 8, display: 'flex', justifyContent: 'center', alignItems: 'center', border: 'none', cursor: 'pointer' },
    addButtonText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 16, margin: 0 },
    listItem: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#FFFFFF', padding: '0 16px', borderRadius: 8, marginBottom: 8, borderBottom: '1px solid #F3F4F6' },
    transparentButton: { background: 'none', border: 'none', cursor: 'pointer', padding: '8px' },
    bigAddButton: { backgroundColor: '#3B82F6', borderRadius: 8, padding: 16, alignItems: 'center', marginBottom: 20, border: 'none', width: '100%', cursor: 'pointer' },
    bigAddButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold', margin: 0 },
    modalContainer: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, display: 'flex', justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)', zIndex: 1000 },
    modalContent: { backgroundColor: '#FFFFFF', borderRadius: 20, padding: 20, width: '90%', maxWidth: 500, maxHeight: '80vh', display: 'flex', flexDirection: 'column' },
    closeButton: { alignSelf: 'flex-end', background: 'none', border: 'none', cursor: 'pointer' },
    modalTitle: { fontSize: 22, fontWeight: 'bold', marginBottom: 20, textAlign: 'center', margin: 0 },
    modalSubtitle: { fontSize: 16, color: '#4B5563', marginBottom: 12, marginTop: 12, margin: 0 },
    habitSelectionContainer: { flex: 1, overflowY: 'auto', border: '1px solid #E5E7EB', borderRadius: 8, padding: '0 10px' },
    habitSelectItem: { display: 'flex', flexDirection: 'row', alignItems: 'center', padding: '12px 0', borderBottom: '1px solid #E5E7EB', cursor: 'pointer' },
    habitSelectText: { marginLeft: 12, fontSize: 16, margin: 0 },
    saveButton: { backgroundColor: '#10B981', borderRadius: 8, padding: 16, alignItems: 'center', marginTop: 20, border: 'none', width: '100%', cursor: 'pointer' },
    saveButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold', margin: 0 },
    routineHabitItem: { display: 'flex', flexDirection: 'row', alignItems: 'center', padding: '8px 0' },
    routineHabitText: { fontSize: 16, color: '#374151', margin: 0 },
    progressBarContainer: { height: 8, backgroundColor: '#E5E7EB', borderRadius: 4, marginBottom: 8, overflow: 'hidden' },
    progressBar: { height: '100%', backgroundColor: '#3B82F6', borderRadius: 4, transition: 'width 0.3s ease' },
    progressText: { fontSize: 12, color: '#6B7280', textAlign: 'right', marginBottom: 10, margin: 0 },
    statsHighlight: { fontSize: 18, fontWeight: 'bold', color: '#3B82F6', margin: '4px 0 16px' },
    statsSubtitle: { fontSize: 16, fontWeight: '500', color: '#1F2937', marginBottom: 8 },
    statsListItem: { display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid #F3F4F6' },
    calendarNav: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' },
    calendarGrid: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '1vw', textAlign: 'center', padding: '1vw' },
    calendarHeader: { fontWeight: 'bold', fontSize: '3vw', color: '#6B7280', marginBottom: '1vw' },
    calendarDay: { 
        aspectRatio: '1 / 1', 
        display: 'flex', 
        flexDirection: 'column',
        justifyContent: 'center', 
        alignItems: 'center', 
        borderRadius: '8px', 
        cursor: 'pointer', 
        borderWidth: '2px',
        borderStyle: 'solid',
        borderColor: 'transparent',
        position: 'relative',
        padding: '0.5vw',
        transition: 'all 0.2s ease-in-out',
    },
    calendarDaySelected: { borderColor: '#3B82F6', transform: 'scale(1.05)' },
    calendarDayNumber: { fontSize: '2.5vw', color: '#374151', fontWeight: '500' },
    calendarDayFraction: { fontSize: '2.2vw', fontWeight: 'bold', color: '#111827' },
    calendarTodayMarker: { position: 'absolute', top: '4px', right: '4px', width: '6px', height: '6px', backgroundColor: '#EF4444', borderRadius: '50%' },
    notificationContainer: { position: 'fixed', top: '20px', left: '50%', transform: 'translateX(-50%)', backgroundColor: '#333', color: 'white', padding: '12px 24px', borderRadius: '8px', zIndex: 2000, boxShadow: '0 4px 6px rgba(0,0,0,0.1)', transition: 'opacity 0.5s ease' },
    notificationText: { margin: 0, fontWeight: '500' },
    confirmModalContent: { backgroundColor: '#FFFFFF', borderRadius: 20, padding: 30, width: '90%', maxWidth: 400, textAlign: 'center', boxShadow: "0 4px 12px rgba(0,0,0,0.15)" },
    confirmButtonContainer: { display: 'flex', justifyContent: 'center', gap: '12px', marginTop: '20px' },
    confirmButton: { padding: '10px 20px', borderRadius: 8, border: 'none', cursor: 'pointer', fontWeight: 'bold', fontSize: 16 },
    cancelButton: { backgroundColor: '#E5E7EB', color: '#374151' },
    okButton: { backgroundColor: '#3B82F6', color: 'white' },
};
